### ISSUE TITLE
Wrong cacerts path

### ISSUE THREAD

**Issue by david-buderus** [upb-uc4/hlf-network#56]
**Describe the bug**
The `org1-ca-cert.pem` is at `/api/org1/cacerts/org1-ca-cert.pem` and not at `/api/org1/msp/cacerts/org1-ca-cert.pem`

**Comment by palkra** [comment]
I think I found the cause of this inconsistent behavior: https://unix.stackexchange.com/questions/172155/syntactic-differences-in-cp-r-and-how-to-overcome-them

**Comment by palkra** [comment]
Nevermind, we just mixed up the `msp` and `org1` in the path...
