### ISSUE TITLE
Improved naming convention for k8s entities

### ISSUE THREAD

**Issue by jonas-thiele** [upb-uc4/hlf-network#61]
The names of our pods, services, secrets,... are sometimes a little too wild, for example `tls-ca-server-ca-key`. it is getting very hard to distinguish certain entitites. Therefore, we should refactor our scripts and configs to establish a more consistent naming pattern.

Proposal: Something along the lines of `uc4.rootca.ca-key` or `uc4.org1.peer2`.

**Comment by palkra** [comment]
The key's names are automatically generated from the names of the components, hence refactoring the names of services and deployments should solve this.

**Comment by palkra** [comment]
I would propose a naming scheme like `peer1.org1` following the subdomain principle. Combined with the namespace this yields `peer1.org1.hlf-production-network.<clustername>` (We should rename the namespace to something shorter)
