### ISSUE TITLE
Make target K8S Cluster configurable

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/hlf-network#67]
**Is your feature request related to a problem? Please describe.**
@david-buderus has to manually overwrite code to deploy to the deployment cluster
```
export K8S_MOUNT=/data/experimental
```

**Describe the solution you'd like**
Provide a parameter in the deploy.sh script which substitutes this value in the env.sh script

**Describe alternatives you've considered**
Let him deal with overwriting it everytime

**Comment by palkra** [comment]
Resolved in #69
