### ISSUE TITLE
Testing flag

### ISSUE THREAD

**Issue by palkra** [upb-uc4/hlf-network#86]
**Is your feature request related to a problem? Please describe.**
For testing the scala API without deploying it to kubernetes, we need to provide certificates, passwords etc. via the filesystem. In the current network, we always provide them, even though it is needed for testing only.

**Describe the solution you'd like**
Implement a testing flag that provides that data only if desired. We could use nodeports only for testing, too (this would probably need some kind of templating).

**Describe alternatives you've considered**
 1. Do not change anything.
 2. Test the API inside the cluster.

**Comment by NikoBergemann** [comment]
Just realized we also use adminName & pw in testcode instead of github secrets. We definately need to hide and then change those to prevent unauthorized access later on

**Comment by palkra** [comment]
We decided to use a flag `-t` which registers an additional user at org1 with the following credentials:
 - Username: test-admin
 - Password: test-admin-pw

**Comment by NikoBergemann** [comment]
user belongs to org1

**Comment by NikoBergemann** [comment]
user has all access rights + registration rights

**Comment by palkra** [comment]
Closed #89
